// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbrxfO062tPIZgQJ6KgbgiEjlHtcZC9g',
    appId: '1:964586820164:web:3ec140d2cac9958dd1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    authDomain: 'cahatapp-3ec8a.firebaseapp.com',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsh3T54tRcPJmpnQiOx4owv_4GHTXxLg',
    appId: '1:964586820164:android:0787eb119ef1c4e4d1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlqMwUSQxb2lCOcNgOKbndnBelwm_CbQ',
    appId: '1:964586820164:ios:8df38581d24c6d88d1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
    iosBundleId: 'com.example.menumo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlqMwUSQxb2lCOcNgOKbndnBelwm_CbQ',
    appId: '1:964586820164:ios:d478549d0a3012d0d1e211',
    messagingSenderId: '964586820164',
    projectId: 'cahatapp-3ec8a',
    storageBucket: 'cahatapp-3ec8a.appspot.com',
    iosBundleId: 'com.example.menumo.RunnerTests',
  );
}
